const $ = id => document.getElementById(id);
let flashKey = null, flashTimer = null, socket = null, activeView = null, latestData = null;
let timingMode = localStorage.getItem('zre-timing-mode') === 'standing' ? 'standing' : 'relative';
let rolePreference=['driver','spotter'].includes(localStorage.getItem('zre-role'))?localStorage.getItem('zre-role'):'auto',activeRole='driver';
const renderCache = new Map(), query = new URLSearchParams(location.search);
const forcedView=query.get('view'),debugEnabled=query.get('debug')==='1';const defaultStrategyConfig={baseStintLaps:37,extendedStintLaps:38,pitLossSeconds:30,manualRaceSeconds:36000,averageLapSeconds:0,consumptionLiters:0,tankCapacityLiters:0,driverNames:['Santiago','David','Herney'],driverAssignments:{}};let strategyConfig=(()=>{try{return {...defaultStrategyConfig,...JSON.parse(localStorage.getItem('zre-strategy-config')||'{}')}}catch(_){return {...defaultStrategyConfig}}})();

function setText(id,value){const el=$(id);if(!el)return;const next=value??'—';if(el.textContent!==String(next))el.textContent=next;}
function rowsSignature(rows){return JSON.stringify(rows||[]);}
function brandLabel(brand,car){const labels={mclaren:'McL',ferrari:'FER',porsche:'POR',lamborghini:'LAM',mercedes:'AMG',bmw:'BMW',audi:'AUD',chevrolet:'CHEV',ford:'FORD',acura:'ACU',astonmartin:'AST'};return labels[brand]||String(car||'CAR').slice(0,4).toUpperCase();}

function timingRows(target,rows,full=false){
 rows=rows||[];const playerIndex=rows.findIndex(row=>row?.isPlayer);if(!full&&playerIndex>=0){const before=rows.slice(Math.max(0,playerIndex-3),playerIndex),player=rows[playerIndex],after=rows.slice(playerIndex+1,playerIndex+4);rows=[...Array.from({length:3-before.length},()=>({isSpacer:true})),...before,player,...after,...Array.from({length:3-after.length},()=>({isSpacer:true}))];}else if(!full)rows=rows.slice(0,7);const signature=rowsSignature(rows);if(renderCache.get(target)===signature)return;renderCache.set(target,signature);
 $(target).replaceChildren(...rows.map(row=>{
  const el=document.createElement('div');if(row.isSpacer){el.className='row timing-spacer';el.setAttribute('aria-hidden','true');return el;}el.className=`row${row.isPlayer?' player':''}`;
  const posNum=document.createElement('div');posNum.className='pos-number';const pos=document.createElement('strong');pos.textContent=`P${row.pos||'—'}`;const num=document.createElement('span');num.textContent=`#${row.number||'—'}`;posNum.append(pos,num);
  const carCell=document.createElement('div');carCell.className='car-cell';const logo=document.createElement('span');logo.className='brand-logo';const fallback=document.createElement('span');fallback.className='brand-fallback';fallback.textContent=brandLabel(row.brand,row.car);
  if(row.brand&&row.brand!=='generic'){const img=document.createElement('img');img.alt=row.brand;img.loading='eager';img.decoding='async';img.src=`https://cdn.simpleicons.org/${row.brand}/FFFFFF`;img.addEventListener('error',()=>{img.hidden=true;fallback.hidden=false;});fallback.hidden=true;logo.append(img,fallback);}else logo.append(fallback);
  const model=document.createElement('span');model.className='car-model';model.textContent=row.car||'—';carCell.append(logo,model);const driver=document.createElement('strong');driver.className='driver';driver.textContent=row.driver||'—';
  const gap=document.createElement('strong');gap.className='gap';gap.textContent=row.gap||'—';const last=document.createElement('span');last.className='time';last.textContent=row.lastLap||'—';const pace=document.createElement('span');pace.className='time';pace.textContent=row.pace||'—';el.append(posNum,carCell,driver,gap,last,pace);return el;
 }));
}
function paceRows(target,rows){rows=rows||[];const signature=rowsSignature(rows);if(renderCache.get(target)===signature)return;renderCache.set(target,signature);$(target).replaceChildren(...rows.map(row=>{const el=document.createElement('div');el.className='pace-row';[row.lap,row.time,row.delta,row.consumption].forEach(value=>{const cell=document.createElement('span');cell.textContent=value??'—';el.append(cell);});return el;}));}
function desiredView(data){if(activeRole==='spotter')return'spotter';if(['live','pit','summary'].includes(driverViewPreference))return driverViewPreference;if(['live','pit','summary'].includes(forcedView))return forcedView;if(data.sessionSummary?.active)return'summary';const pit=data.self?.pit;return pit&&pit!=='EN PISTA'?'pit':'live';}
function switchView(view){if(activeView===view)return;activeView=view;document.body.dataset.view=view;$('live-view').hidden=view!=='live';$('pit-view').hidden=view!=='pit';$('summary-view').hidden=view!=='summary';$('spotter-view').hidden=view!=='spotter';setText('view-badge',view==='spotter'?'SPOTTER':view==='live'?'PISTA':(view==='pit'?'PIT / GARAGE':'RESUMEN'));}
function renderHeader(data){setText('car',data.header?.car);setText('track',data.header?.track);setText('header-driver',data.header?.driver);setText('header-position',data.header?.position);setText('header-lap',data.header?.lap);setText('state',data.header?.state);document.querySelector('.session-state')?.classList.toggle('offline',!data.connected);const controls=$('coach-controls');if(controls)controls.hidden=!data.capabilities?.coachControls;}
let spotterRivalCandidates=[];
function refreshSpotterRivalOptions(rival){
 const rsel=$('spotter-rival-select');if(!rsel)return;
 spotterRivalCandidates=rival?.candidates||[];
 const query=String($('spotter-rival-filter')?.value||'').trim().toLowerCase();
 const filtered=spotterRivalCandidates.filter(item=>!query||String(item.label||'').toLowerCase().includes(query)||String(item.position||'').toLowerCase().includes(query));
 const current=rival?.mode==='manual'&&rival?.selectedIdx!=null?String(rival.selectedIdx):'auto';
 rsel.replaceChildren(new Option('AUTO · rival estratégico','auto'),...filtered.map(item=>new Option(`${item.position} · ${item.label}`,String(item.idx))));
 if([...rsel.options].some(o=>o.value===current))rsel.value=current;
 setText('spotter-rival-mode',rival?.mode==='manual'?'FIJO':'AUTO');
 const autoButton=$('spotter-rival-auto');if(autoButton){autoButton.classList.toggle('active',rival?.mode!=='manual');autoButton.setAttribute('aria-pressed',String(rival?.mode!=='manual'));}
}
function renderStopPlan(plan){const target=$('spotter-stop-plan');if(!target)return;const stops=plan?.stops||[];const signature=JSON.stringify(stops)+JSON.stringify(plan?.completed||[])+JSON.stringify(strategyConfig.driverNames||[])+JSON.stringify(plan?.warnings||[]);if(renderCache.get('spotter-stop-plan')===signature)return;if(target.contains(document.activeElement))return;renderCache.set('spotter-stop-plan',signature);
 if(!plan?.available){target.textContent='Configura ritmo, tiempo, fuel, consumo y capacidad para proyectar paradas.';return;}
 if(!stops.length){target.textContent='Sin paradas pendientes · BANDERA';return;}
 target.replaceChildren(...stops.map(stop=>{const row=document.createElement('div');row.className='stop-plan-row';row.dataset.stop=String(stop.number);
 const title=document.createElement('strong');title.textContent=`PARADA ${stop.number} · ${stop.status.toUpperCase()}`;
 const summary=document.createElement('span');summary.textContent=`AUTO V${stop.suggestedLap} · ${stop.autoDriver||'PILOTO —'} · ${stop.autoFuel}${stop.source==='MANUAL'?' · MANUAL':''}`;
 const lap=document.createElement('input');lap.type='number';lap.min='1';lap.placeholder='VUELTA AUTO';lap.value=stop.manualLap??'';lap.dataset.field='lap';
 const driver=document.createElement('select');driver.dataset.field='driver';driver.append(new Option('PILOTO AUTO','auto'),...(strategyConfig.driverNames||[]).map(name=>new Option(name,name)));driver.value=stop.manualDriver||'auto';
 const fuel=document.createElement('select');fuel.dataset.field='fuel';[['auto','FUEL AUTO'],['fill','LLENAR'],['none','SIN REPOSTAR'],['add','+ LITROS']].forEach(([v,t])=>fuel.add(new Option(t,v)));fuel.value=stop.fuelAction||'auto';
 const liters=document.createElement('input');liters.type='number';liters.min='0.1';liters.step='0.1';liters.placeholder='LITROS AUTO';liters.value=stop.manualLiters??'';liters.dataset.field='liters';
 const info=document.createElement('small');info.textContent=`PLAN V${stop.lap} · ${stop.driver||'—'} · ${stop.liters==null?'FUEL SIN DATO':`${stop.liters} L`}`;
 row.append(title,summary,lap,driver,fuel,liters,info);return row;}));
 if(plan.warnings?.length){const warning=document.createElement('p');warning.textContent=plan.warnings.join(' · ');target.append(warning);}}
$('spotter-stop-plan')?.addEventListener('change',event=>{const control=event.target,field=control.dataset.field,number=Number(control.closest('[data-stop]')?.dataset.stop);if(!field||!number)return;const value=control.value||null;if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'stopOverride',number,field,value}));renderCache.delete('spotter-stop-plan');});$('spotter-stop-plan')?.addEventListener('focusout',()=>setTimeout(()=>{if(latestData)renderStopPlan(latestData.racePlan||latestData.enduranceStrategy?.stopPlan);},150));
function renderSpotter(data){const team=data.teamContext||{},strategy=data.enduranceStrategy||{},rival=data.raceDirector||{};
 const plan=data.racePlan||strategy.stopPlan||{};
 const fields={'spotter-car':team.carNumber?`#${team.carNumber}`:data.header?.car,'spotter-driver':`Piloto: ${team.driver||'AUTO · no confirmado'}${team.driverSource==='MANUAL'?' · MANUAL':''}`,'spotter-position':data.header?.position,'spotter-lap':data.header?.lap,'spotter-time':team.remainingTime,'spotter-fuel':data.self?.fuel,'spotter-autonomy':plan.autonomyLaps==null?'—':`${plan.autonomyLaps} vueltas · EST.`,'spotter-next-stop':plan.stops?.length?`VUELTA ${plan.stops[0].lap}`:'—','spotter-stops':plan.stopsRemaining,'spotter-rival-name':rival.rival,'spotter-rival-pos':rival.position,'spotter-rival-gap':rival.gap,'spotter-rival-last':rival.lastLap,'spotter-rival-lap':rival.lap,'spotter-rival-pit':rival.pit};Object.entries(fields).forEach(([id,value])=>setText(id,value));
 $('spotter-identity-warning').hidden=team.carIdx!=null;setText('spotter-control-status',team.controlError||`${team.fuelState||'NO DISPONIBLE'} · ${team.manualEvents?.length||0} eventos`);
 timingRows('spotter-relative-rows',data.relative||[]);timingRows('spotter-standing-rows',data.standing||[]);timingRows('spotter-standing-all',data.standingAll||data.standing||[],true);
 setText('spotter-relative-count',`· ${data.relativeAvailableCars??0} coches con posición disponible`);
 if(!data.relative?.length)setText('spotter-relative-rows','NO DISPONIBLE · sin posición dinámica del coche');if(!data.standing?.length)setText('spotter-standing-rows','NO DISPONIBLE · revisa COCHE DEL EQUIPO');
 setText('spotter-plan-summary',`Vueltas proyectadas: ${plan.projectedLaps??'—'} · autonomía: ${plan.autonomyLaps??'—'} · mínimo paradas: ${plan.minimumStops??'—'}`);
 const stops=plan.completed||[];setText('spotter-stop-history',stops.length?stops.map(x=>`P${x.number} · V${x.lap??'—'} · ${x.status==='detected'?'PARADA DETECTADA':'COMPLETADA'} · ${x.fuel||'PENDIENTE'}${x.driver?' · '+x.driver:''}`).join(' | '):'SIN PARADAS');renderStopPlan(plan);
 const choices=team.teamChoices||[],select=$('team-car-select'),signature=JSON.stringify(choices);if(renderCache.get('team-car-choices')!==signature){renderCache.set('team-car-choices',signature);const auto=document.createElement('option');auto.value='auto';auto.textContent='AUTO';select.replaceChildren(auto,...choices.map(item=>{const option=document.createElement('option');option.value=String(item.idx);option.dataset.number=item.number||'';option.textContent=item.label;return option}));select.value=localStorage.getItem('zre-team-car')||'auto';}
 refreshSpotterRivalOptions(rival);
 const names=strategyConfig.driverNames||[],dsel=$('spotter-driver-select'),nsig=JSON.stringify(names);if(renderCache.get('spotter-driver-choices')!==nsig){renderCache.set('spotter-driver-choices',nsig);dsel.replaceChildren(...names.map(name=>new Option(name,name)));}if(team.driver&&names.some(n=>n.toLowerCase()===team.driver.toLowerCase())&&document.activeElement!==dsel)dsel.value=names.find(n=>n.toLowerCase()===team.driver.toLowerCase());
}


function drawTrackMap(trackMap,lineId,markersId,locationId,emptyId=null){
 const line=$(lineId),markers=$(markersId),points=trackMap?.points||[],spots=trackMap?.markers||[],hasTrace=points.length>10;if(emptyId&&$(emptyId))$(emptyId).hidden=hasTrace;if(!line||!markers)return false;
 line.setAttribute('points',hasTrace?points.map(p=>`${p.x},${p.y}`).join(' '):'');
 markers.replaceChildren(...spots.map((spot,index)=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`loss-marker loss-marker-${index+1}`);const halo=document.createElementNS('http://www.w3.org/2000/svg','circle');halo.setAttribute('cx',spot.x);halo.setAttribute('cy',spot.y);halo.setAttribute('r',index?'3.3':'4.4');const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',spot.x);dot.setAttribute('cy',spot.y);dot.setAttribute('r',index?'1.35':'1.8');const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',spot.x+3);text.setAttribute('y',spot.y-3);text.textContent=`+${Number(spot.loss||0).toFixed(2)}s`;g.append(halo,dot,text);return g;}));
 const main=spots[0];if(locationId){const source=trackMap?.source?`${trackMap.source} · `:'';setText(locationId,main?`${source}${main.label} · +${Number(main.loss||0).toFixed(2)}s`:(hasTrace?`${source}SIN PÉRDIDA PRIORITARIA`:'CONSTRUYENDO STINT'));}return hasTrace;
}
function renderTrackMap(trackMap){const card=$('flash-map-card'),visible=Boolean(trackMap?.points?.length>10&&trackMap?.markers?.length);if(card)card.hidden=!visible;if(visible)drawTrackMap(trackMap,'flash-track-line','flash-track-markers','flash-map-location');}
function renderLiveTrackMap(trackMap){drawTrackMap(trackMap,'live-track-line','live-track-markers','live-map-location','live-map-empty');}
function renderLapFlash(data){const summary=data.lastLapSummary,flash=$('lap-flash'),visible=Boolean(summary&&summary.expiresAt>Date.now()/1000),nextFlashKey=visible?`${summary.lap}-${summary.expiresAt}`:null;if(visible&&nextFlashKey!==flashKey){flashKey=nextFlashKey;flash.hidden=false;clearTimeout(flashTimer);flashTimer=setTimeout(()=>{flash.hidden=true;},Math.max(0,summary.expiresAt*1000-Date.now()));}else if(!visible)flash.hidden=true;if(!visible)return;setText('flash-lap',summary.lap);setText('flash-time',summary.time);setText('flash-best',summary.sessionBest);setText('flash-delta',summary.delta);$('flash-delta').classList.toggle('negative',String(summary.delta||'').startsWith('-'));renderTrackMap(data.coach?.trackMap);const coachText=data.coach?.lapMessage;$('flash-coach').hidden=!coachText;if(coachText)setText('flash-coach',coachText);}

function renderRival(d){d=d||{};setText('rival-mode',d.mode==='manual'?'MANUAL':'AUTO');setText('rival-name',d.rival||'—');setText('rival-status',d.status||'Esperando rivales de clase');setText('rival-position',d.position||'—');setText('rival-gap',d.gap||'—');setText('rival-last',d.lastLap||'—');setText('rival-lap',d.lap||'—');const select=$('rival-select');if(!select)return;const candidates=d.candidates||[],sig=JSON.stringify(candidates.map(x=>[x.idx,x.label,x.position]));if(select.dataset.signature!==sig){select.dataset.signature=sig;const auto=document.createElement('option');auto.value='auto';auto.textContent='AUTO';select.replaceChildren(auto,...candidates.map(item=>{const o=document.createElement('option');o.value=String(item.idx);o.textContent=`${item.position} · ${item.label}`;return o}))}select.value=d.mode==='manual'&&d.selectedIdx!=null?String(d.selectedIdx):'auto';}
function strategyInputValue(id,value){const el=$(id);if(!el||document.activeElement===el)return;const next=value??0;if(String(el.value)!==String(next))el.value=next}
function renderStrategyTimeline(strategy,targetId='strategy-timeline'){const target=$(targetId);if(!target)return;const rows=strategy?.timeline||[],sig=JSON.stringify(rows)+JSON.stringify(strategyConfig.driverAssignments||{});if(renderCache.get(targetId)===sig)return;renderCache.set(targetId,sig);if(!rows.length){const empty=document.createElement('span');empty.className='timeline-empty';empty.textContent='Esperando proyección…';target.replaceChildren(empty);return}target.replaceChildren(...rows.map(item=>{const chip=document.createElement('button');chip.type='button';chip.className=`stint-chip ${item.status||'future'}${item.double?' double':''}`;const title=document.createElement('strong');title.textContent=`S${item.number} · ${item.laps}v${item.status==='done'?' ✓':''}`;const driver=document.createElement('b');driver.textContent=item.driver||'SIN ASIGNAR';const end=document.createElement('span');end.textContent=item.status==='current'?`→ V${item.endLap}`:(item.endLap?`V${item.endLap}`:'');chip.append(title,driver,end);if(item.status!=='done')chip.addEventListener('click',()=>cycleStintDriver(item.number,item.driver));else chip.disabled=true;return chip}))}
function renderEnduranceStrategy(strategy){strategy=strategy||{};const card=$('endurance-strategy-card');if(card)card.dataset.state=strategy.state||'idle';setText('strategy-verdict',strategy.available?strategy.verdict:(strategy.reason||'ESPERANDO DATOS'));setText('strategy-current-stint',strategy.currentStint||'—');setText('strategy-driver',strategy.currentDriver||'—');setText('strategy-box-lap',strategy.boxLap||'—');setText('strategy-autonomy',strategy.autonomy||'—');setText('strategy-stops',strategy.stopsRemaining??'—');setText('strategy-avoidable',strategy.available?(strategy.lastStopAvoidable?'EVITABLE':'NO'):'—');setText('strategy-extension',strategy.available?`+${strategy.extensionNeeded||0} vueltas`:'—');setText('strategy-target',strategy.targetThisStint||'—');setText('strategy-base',strategy.base?`BASE ${strategy.base.stintLaps}v · ${strategy.base.stops} paradas · final ${strategy.base.lastStintLaps}v`:'BASE —');setText('strategy-extended',strategy.extended?`EXT. ${strategy.extended.stintLaps}v · ${strategy.extended.stops} paradas · final ${strategy.extended.lastStintLaps}v`:'EXT. —');setText('strategy-remaining-time',strategy.remainingTime?`RESTANTE ${strategy.remainingTime}`:'—');renderStrategyTimeline(strategy);const settings=strategy.settings||{};strategyInputValue('strategy-base-input',settings.baseStintLaps??strategyConfig.baseStintLaps);strategyInputValue('strategy-extended-input',settings.extendedStintLaps??strategyConfig.extendedStintLaps);strategyInputValue('strategy-pit-loss-input',settings.pitLossSeconds??strategyConfig.pitLossSeconds)}
function saveStrategyConfig(){localStorage.setItem('zre-strategy-config',JSON.stringify(strategyConfig));sendSetting('strategy',strategyConfig);renderCache.delete('strategy-timeline');renderCache.delete('spotter-timeline')}
function readStrategyInputs(){const num=(id,f=0)=>{const v=Number($(id)?.value);return Number.isFinite(v)?v:f};strategyConfig.baseStintLaps=Math.max(1,Math.round(num('strategy-base-input',37)));strategyConfig.extendedStintLaps=Math.max(strategyConfig.baseStintLaps,Math.round(num('strategy-extended-input',38)));strategyConfig.pitLossSeconds=Math.max(0,num('strategy-pit-loss-input',30));strategyConfig.manualRaceSeconds=Math.max(0,num('strategy-race-hours-input',10)*3600);strategyConfig.averageLapSeconds=Math.max(0,num('strategy-lap-input',0));strategyConfig.consumptionLiters=Math.max(0,num('strategy-consumption-input',0));strategyConfig.tankCapacityLiters=Math.max(0,num('strategy-tank-input',0));strategyConfig.driverNames=String($('strategy-drivers-input')?.value||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,6);saveStrategyConfig()}
function cycleStintDriver(number,current){const names=strategyConfig.driverNames||[];if(!names.length)return;const index=names.indexOf(current),next=names[(index+1)%names.length];strategyConfig.driverAssignments={...(strategyConfig.driverAssignments||{}),[String(number)]:next};saveStrategyConfig();if(latestData?.enduranceStrategy)renderStrategyTimeline(latestData.enduranceStrategy)}
function renderLive(data){const rows=timingMode==='standing'?data.standing:data.relative;timingRows('timing-rows',rows);setText('timing-title',timingMode==='standing'?'CLASIFICACIÓN':'RELATIVO');if($('timing-mode'))$('timing-mode').value=timingMode;renderLiveTrackMap(data.coach?.trackMap);renderRival(data.raceDirector);renderEnduranceStrategy(data.enduranceStrategy);paceRows('pace-rows',data.self?.laps);setText('fuel',data.self?.fuel);setText('last-use',data.self?.lastUse);setText('best-use',data.self?.bestUse);setText('worst-use',data.self?.worstUse);setText('last-lap',data.self?.lastLap);setText('best-lap',data.self?.bestLap);setText('optimal-lap',data.coach?.optimalLap||'—');setText('wear-fl',data.self?.wear?.FL);setText('wear-fr',data.self?.wear?.FR);setText('wear-rl',data.self?.wear?.RL);setText('wear-rr',data.self?.wear?.RR);setText('pit',data.self?.pit);setText('pit-window',data.self?.pitWindow);setText('next-stop',data.self?.nextStop);}
function priorityParts(priority,fallbackZone,fallbackTitle,fallbackAdvice){return{zone:priority?.zone||fallbackZone,title:priority?.title||priority?.cause||fallbackTitle,advice:priority?.advice||fallbackAdvice};}
function renderPit(data){const coach=data.coach||{},strategy=data.strategy||{},director=data.raceDirector||{};setText('coach-reference',coach.reference||'ÓPTIMA SESIÓN');setText('pit-best-lap',coach.bestLap||data.self?.bestLap||'—');setText('pit-optimal-lap',coach.optimalLap||'—');setText('pit-potential',coach.potential||'—');const primary=priorityParts(coach.primary,'REFERENCIA','Construyendo referencia','El análisis aparecerá aquí cuando existan suficientes vueltas comparables.'),secondary=priorityParts(coach.secondary,'PATRÓN',coach.pattern||'—',coach.patternAdvice||'—');setText('coach-primary-zone',primary.zone);setText('coach-primary-title',primary.title);setText('coach-primary-advice',primary.advice);setText('coach-secondary-zone',secondary.zone);setText('coach-secondary-title',secondary.title);setText('coach-secondary-advice',secondary.advice);setText('pit-state-badge',data.self?.pit||'GARAGE');setText('pit-fuel',data.self?.fuel);setText('pit-consumption',strategy.consumption||data.self?.lastUse);setText('pit-next-stop',strategy.nextStop||data.self?.nextStop);setText('pit-add-fuel',strategy.addFuel||'—');setText('pit-laps-remaining',strategy.lapsRemaining||'—');setText('director-confidence',director.confidence||'SIN DATOS');setText('director-rival',director.rival||'—');setText('director-status',director.status||'Esperando contexto de carrera.');setText('director-gap-before',director.gapBefore||'—');setText('director-net-gap',director.netGap||'—');timingRows('pit-standing-rows',data.standing);paceRows('pit-pace-rows',data.self?.laps);}
function renderSummary(data){const summary=data.sessionSummary||{};setText('summary-best',summary.bestLap||data.self?.bestLap||'—');setText('summary-optimal',summary.optimalLap||data.coach?.optimalLap||'—');setText('summary-potential',summary.potential||data.coach?.potential||'—');setText('summary-laps',summary.lapCount??data.self?.laps?.length??'—');paceRows('summary-pace-rows',data.self?.laps);const priorities=summary.priorities||[],target=$('summary-priorities'),signature=rowsSignature(priorities);if(renderCache.get('summary-priorities')!==signature){renderCache.set('summary-priorities',signature);target.replaceChildren(...(priorities.length?priorities:[{zone:'RESUMEN',title:'Sin análisis todavía',advice:'El resumen detallado aparecerá al finalizar una sesión analizada.'}]).map(item=>{const el=document.createElement('div');el.className='summary-priority';const zone=document.createElement('span');zone.textContent=item.zone||'ZONA';const title=document.createElement('strong');title.textContent=item.title||item.cause||'—';const advice=document.createElement('p');advice.textContent=item.advice||'—';el.append(zone,title,advice);return el;}));}}
let teamDebugOpen=false;function renderDebug(data){const panel=$('debug-panel');if(!panel)return;panel.hidden=!(debugEnabled||teamDebugOpen);if(!(debugEnabled||teamDebugOpen))return;const d=data.coach?.diagnostics||{};$('debug-content').textContent=JSON.stringify({team:data.teamDebug||{},connected:data.connected,pit:data.self?.pit,lap:data.header?.lap,best:data.coach?.bestLap,optimal:data.coach?.optimalLap,potential:data.coach?.potential,accepted:d.accepted,sampleBins:d.sampleBins,zonesCompared:d.zonesCompared,advice:d.advice||[]},null,2);}
function render(data){latestData=data;activeRole=rolePreference==='auto'?(data.teamContext?.autoMode||'driver'):rolePreference;document.body.dataset.role=activeRole;$('driver-view-control').hidden=activeRole==='spotter';$('demo-role-control').hidden=!data.demo;const view=desiredView(data);switchView(view);renderHeader(data);if(activeRole==='spotter')$('lap-flash').hidden=true;else renderLapFlash(data);renderDebug(data);if(view==='live')renderLive(data);else if(view==='pit')renderPit(data);else if(view==='summary')renderSummary(data);else renderSpotter(data);setText('notice',data.demo?`Modo demostración · vista ${view.toUpperCase()}`:(data.connected?'Telemetría de iRacing en directo':'iRacing no detectado · último estado válido conservado'));}

$('driver-view-select').addEventListener('change',event=>{driverViewPreference=event.target.value;if(latestData)render(latestData);});$('team-debug-toggle').addEventListener('click',()=>{teamDebugOpen=!teamDebugOpen;$('team-debug-toggle').setAttribute('aria-pressed',String(teamDebugOpen));if(latestData)renderDebug(latestData);else $('debug-panel').hidden=!teamDebugOpen;});$('role-select').value=rolePreference;$('role-select').addEventListener('change',event=>{rolePreference=event.target.value;localStorage.setItem('zre-role',rolePreference);sendSetting('role',rolePreference);if(latestData)render(latestData);});$('demo-role-select').addEventListener('change',event=>sendSetting('demoRole',event.target.value));$('team-car-select').addEventListener('change',event=>{localStorage.setItem('zre-team-car',event.target.value);const number=event.target.selectedOptions[0]?.dataset.number||'';localStorage.setItem('zre-team-car-number',number);sendSetting('teamCar',event.target.value);sendSetting('teamCarNumber',number);});$('spotter-rival-select').addEventListener('change',event=>sendSetting('rival',event.target.value));
$('spotter-rival-auto')?.addEventListener('click',()=>{sendSetting('rival','auto');if($('spotter-rival-select'))$('spotter-rival-select').value='auto';setText('spotter-rival-mode','AUTO');});
$('spotter-rival-filter')?.addEventListener('input',()=>refreshSpotterRivalOptions(latestData?.raceDirector||{}));$('team-driver-input').addEventListener('change',event=>sendSetting('teamDriver',event.target.value));const timingSelect=$('timing-mode');if(timingSelect)timingSelect.value=timingMode;timingSelect?.addEventListener('change',e=>{timingMode=e.target.value==='standing'?'standing':'relative';localStorage.setItem('zre-timing-mode',timingMode);renderCache.delete('timing-rows');if(latestData&&activeView==='live')renderLive(latestData);});$('rival-select')?.addEventListener('change',e=>sendSetting('rival',e.target.value));['strategy-base-input','strategy-extended-input','strategy-pit-loss-input','strategy-race-hours-input','strategy-lap-input','strategy-consumption-input','strategy-tank-input','strategy-drivers-input'].forEach(id=>$(id)?.addEventListener('change',readStrategyInputs));strategyInputValue('strategy-base-input',strategyConfig.baseStintLaps);strategyInputValue('strategy-extended-input',strategyConfig.extendedStintLaps);strategyInputValue('strategy-pit-loss-input',strategyConfig.pitLossSeconds);strategyInputValue('strategy-race-hours-input',(strategyConfig.manualRaceSeconds||36000)/3600);strategyInputValue('strategy-lap-input',strategyConfig.averageLapSeconds||0);strategyInputValue('strategy-consumption-input',strategyConfig.consumptionLiters||0);strategyInputValue('strategy-tank-input',strategyConfig.tankCapacityLiters||0);if($('strategy-drivers-input'))$('strategy-drivers-input').value=(strategyConfig.driverNames||[]).join(', ');
function sendSpotterEvent(action){const event={type:'spotterEvent',action,id:`${Date.now()}-${Math.random().toString(36).slice(2)}`,driver:$('spotter-driver-select').value,liters:$('spotter-added-liters').value};if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(event));else setText('spotter-control-status','Sin conexión con el servidor');}
document.querySelectorAll('[data-spotter-action]').forEach(button=>button.addEventListener('click',()=>sendSpotterEvent(button.dataset.spotterAction)));$('spotter-fuel-submit').addEventListener('click',()=>sendSpotterEvent($('spotter-fuel-action').value));
$('spotter-tank-input').value=strategyConfig.tankCapacityLiters||'';$('spotter-consumption-input').value=strategyConfig.consumptionLiters||'';['spotter-tank-input','spotter-consumption-input'].forEach(id=>$(id).addEventListener('change',()=>{strategyConfig.tankCapacityLiters=Number($('spotter-tank-input').value)||0;strategyConfig.consumptionLiters=Number($('spotter-consumption-input').value)||0;saveStrategyConfig();}));
function sendSetting(key,value){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'settings',key,value}));}
$('reference-select')?.addEventListener('change',e=>sendSetting('reference',e.target.value));const audioSelect=$('audio-select'),savedAudio=localStorage.getItem('iracing-audio-mode');if(audioSelect&&['off','lap'].includes(savedAudio))audioSelect.value=savedAudio;audioSelect?.addEventListener('change',e=>{localStorage.setItem('iracing-audio-mode',e.target.value);sendSetting('audio',e.target.value);});$('audio-test')?.addEventListener('click',()=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'action',action:'audio_test'}));});
let webBuildReloading=false,buildCheckPending=false,reconnectTimer=null;
async function checkInstalledWebBuild(){if(webBuildReloading||buildCheckPending)return;buildCheckPending=true;try{const response=await fetch(`/version?fresh=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const status=await response.json();const pageBuild=document.querySelector('meta[name="zre-build"]')?.content;const installed=status.installedVersion;if(installed&&pageBuild&&installed!==pageBuild&&sessionStorage.getItem('zre-reload-attempt')!==installed){sessionStorage.setItem('zre-reload-attempt',installed);webBuildReloading=true;location.replace(`/?v=${encodeURIComponent(installed)}&fresh=${Date.now()}`);}else if(installed===pageBuild){sessionStorage.removeItem('zre-reload-attempt');}}catch(_){}finally{buildCheckPending=false;}}
function connect(){if(webBuildReloading||socket&&[WebSocket.CONNECTING,WebSocket.OPEN].includes(socket.readyState))return;const ws=new WebSocket(`ws://${location.host}/ws`);socket=ws;ws.onopen=()=>{if(socket===ws){sendSetting('audio',audioSelect?.value||'off');sendSetting('strategy',strategyConfig);sendSetting('role',rolePreference);sendSetting('teamCar',localStorage.getItem('zre-team-car')||'auto');sendSetting('teamCarNumber',localStorage.getItem('zre-team-car-number')||'');sendSetting('demoRole',$('demo-role-select').value);}};ws.onmessage=event=>{if(socket===ws)render(JSON.parse(event.data));};ws.onclose=()=>{if(socket!==ws||webBuildReloading)return;socket=null;if(reconnectTimer===null)reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect();},2000);};}connect();checkInstalledWebBuild();setInterval(checkInstalledWebBuild,5000);
